### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by Froggy-The-Frog** [Rdimo/Hazard-Nuker#140]
C:\Users\MSI\OneDrive\Bureau\Hazard-Nuker-master>python hazard.py
Traceback (most recent call last):
  File "hazard.py", line 11, in <module>
    import util.accountNuke
  File "C:\Users\MSI\OneDrive\Bureau\Hazard-Nuker-master\util\accountNuke.py", line 7, in <module>
    import Hazard
  File "C:\Users\MSI\OneDrive\Bureau\Hazard-Nuker-master\Hazard.py", line 16, in <module>
    import util.massreport
  File "C:\Users\MSI\OneDrive\Bureau\Hazard-Nuker-master\util\massreport.py", line 38
    if (status := report.status_code) == 201:
               ^
SyntaxError: invalid syntax

when i opened hazard it say this

**Comment by GTF0** [comment]
maybe you didnt install some modules but my ass is having some real issues using hazard after the new update

**Comment by Rdimo** [comment]
damn so update was for the worse? b r u h

**Comment by Rdimo** [comment]
ill fix everything soon hold on

**Comment by GTF0** [comment]
oof
