### ISSUE TITLE
Hazard Nuker [BUG]

### ISSUE THREAD

**Issue by DD2476** [Rdimo/Hazard-Nuker#178]
**Describe the bug**
(quick word: I have replaced the token with [token] and the user with [user])
On almost all the functions, whether the chrome driver is running or not, I get this error message:
```
[>>>] Choice: 9
[>>>] Token: [token]

Checking Driver. . .
chromedriver.exe already exists, continuing. . .
Traceback (most recent call last):
  File "C:\Users\[user]\Desktop\HazardNuker\hazard.py", line 531, in <module>
    main()
  File "C:\Users\[user]\Desktop\HazardNuker\hazard.py", line 244, in main
    util.login.TokenLogin(token)
  File "C:\Users\[user]\Desktop\HazardNuker\util\login.py", line 28, in TokenLogin
    driver = webdriver.Chrome(options=opts)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.
Stacktrace:
Backtrace:
        Ordinal0 [0x0113B8F3+2406643]
        Ordinal0 [0x010CAF31+1945393]
        Ordinal0 [0x00FBC748+837448]
        Ordinal0 [0x00FD8702+952066]
        Ordinal0 [0x00FD5D71+941425]
        Ordinal0 [0x01008EE0+1150688]
        Ordinal0 [0x01008B3A+1149754]
        Ordinal0 [0x01004096+1130646]
        Ordinal0 [0x00FDE636+976438]
        Ordinal0 [0x00FDF546+980294]
        GetHandleVerifier [0x013A9612+2498066]
        GetHandleVerifier [0x0139C920+2445600]
        GetHandleVerifier [0x011D4F2A+579370]
        GetHandleVerifier [0x011D3D36+574774]
        Ordinal0 [0x010D1C0B+1973259]
        Ordinal0 [0x010D6688+1992328]
        Ordinal0 [0x010D6775+1992565]
        Ordinal0 [0x010DF8D1+2029777]
        BaseThreadInitThunk [0x7770FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77A07A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77A07A4E+238]
```

**Comment by dekrypted** [comment]
Do you have Chrome Browser installed?
(And the proper corresponding chromedriver version?)
