### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by cybernze** [Rdimo/Hazard-Nuker#183]
C:\Users\Carlos\Desktop\Hazard-Nuker-master\Hazard-Nuker-master>python hazard.py
Traceback (most recent call last):
  File "C:\Users\Carlos\Desktop\Hazard-Nuker-master\Hazard-Nuker-master\hazard.py", line 9, in <module>
    from util.plugins.common import *
  File "C:\Users\Carlos\Desktop\Hazard-Nuker-master\Hazard-Nuker-master\util\plugins\common.py", line 18, in <module>
    import pylibcheck
  File "C:\Users\Carlos\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pylibcheck\__init__.py", line 6, in <module>
    __python__ = Path(sys.executable).resolve()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\Carlos\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe'

**Comment by cybernze** [comment]
??

**Comment by dekrypted** [comment]
Please provide more information. Just the Error is not helpful. We need context.

**Comment by Robinline95** [comment]
> Please provide more information. Just the Error is not helpful. We need context.

i have the same issue. This happens when you run start.bat after installing all the recquirements

**Comment by Smug246** [comment]
dm me on cord Smug#6469 i can help
