### ISSUE TITLE
Hazard Nuker [BUG]

### ISSUE THREAD

**Issue by kasperinjo** [Rdimo/Hazard-Nuker#192]
Succesfully turned Name#0000 into a Hazardous Wasteland Enter anything to continue. . . *I click enter*
Traceback (most recent call last):
  File "Hazard.py", line 514, in <module>
  File "Hazard.py", line 237, in main
  File "util\info.py", line 160, in Info
  File "Hazard.py", line 244, in main
  File "util\login.py", line 70, in TokenLogin
  File "Hazard.py", line 204, in main
  File "Hazard.py", line 204, in <listcomp>
TypeError: unhashable type: 'slice'
[13276] Failed to execute script 'Hazard' due to unhandled exception!

**Comment by dekrypted** [comment]
@Rdimo I don't know about this one lol...
