### ISSUE TITLE
Hazard Nuker [HELP] PLS

### ISSUE THREAD

**Issue by MRXCLAYZERO** [Rdimo/Hazard-Nuker#207]
So when i want to start Hazard.py i get this error in the cmd:Traceback (most recent call last):
  File "C:\Users\CENSORED\Desktop\hazard\Hazard.py", line 9, in <module>
    from util.plugins.common import *
  File "C:\Users\CENSORED\Desktop\hazard\util\plugins\common.py", line 18, in <module>
    import pylibcheck
  File "C:\Users\CENSORED\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pylibcheck\__init__.py", line 6, in <module>
    __python__ = Path(sys.executable).resolve()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1920] The system cannot access the file: 'C:\\Users\\CENSORED\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe'

My Operating System is Windows 11

![unknown (1)](https://user-images.githubusercontent.com/76757293/173653323-fb98f642-0fc7-4ed2-9cae-796a6f33198e.png)

**Comment by Rexxboy02** [comment]
Compiled version or source code?

**Comment by MRXCLAYZERO** [comment]
> Compiled version or source code?
source code

**Comment by MRXCLAYZERO** [comment]
> Compiled version or source code?

where is the compiled version?

**Comment by omnituensaeternum** [comment]
At your mothers house
