### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by lukaz34** [Rdimo/Hazard-Nuker#236]
When use the start.bat it says:
Traceback (most recent call last):
  File "C:\Users\Lukas\Desktop\Hazard-Nuker-master\hazard.py", line 14, in <module>
    import util.accountNuke
  File "C:\Users\Lukas\Desktop\Hazard-Nuker-master\util\accountNuke.py", line 7, in <module>
    import Hazard
  File "C:\Users\Lukas\Desktop\Hazard-Nuker-master\Hazard.py", line 26, in <module>
    import util.create_token_grabber
  File "C:\Users\Lukas\Desktop\Hazard-Nuker-master\util\create_token_grabber.py", line 13, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

Wondows 10 Pro

I have tried 'pip install crypto' and 'pip install pycryptodome'

![unknown](https://user-images.githubusercontent.com/101516623/180736542-70a7117d-67c7-4554-82a3-54bc43d8d861.png)

**Comment by timmywag** [comment]
sucks 2 suck

**Comment by dekrypted** [comment]
Make sure you've installed pycryptodome!
`pip install pycryptodome`

**Comment by lukaz34** [comment]
> 

I have but i still get the same error
