### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by hiraxx214** [Rdimo/Hazard-Nuker#43]
hi when i open hazard.py and this is whats i got

Traceback (most recent call last):
  File "C:\Users\alienware\Desktop\Selfbots\Hazard-Nuker-master\hazard.py", line 12, in <module>
    import util.accountNuke
  File "C:\Users\alienware\Desktop\Selfbots\Hazard-Nuker-master\util\accountNuke.py", line 7, in <module>
    import Hazard
  File "C:\Users\alienware\Desktop\Selfbots\Hazard-Nuker-master\Hazard.py", line 15, in <module>
    import util.login
  File "C:\Users\alienware\Desktop\Selfbots\Hazard-Nuker-master\util\login.py", line 4, in <module>
    import undetected_chromedriver as uc
  File "D:\lib\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "D:\lib\site-packages\undetected_chromedriver\v2.py", line 24, in <module>
    from .cdp import CDP
  File "D:\lib\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (D:\lib\collections\__init__.py)

**Comment by hiraxx214** [comment]
the problem was my python version rdimo helped in his discord thanks for the support you need python version 3.9.7
