### ISSUE TITLE
Hazard Nuker [BUG]

### ISSUE THREAD

**Issue by Omar999997** [Rdimo/Hazard-Nuker#91]
THe qr code is not working for me

<img width="960" alt="image" src="https://user-images.githubusercontent.com/88018560/152023264-11f2452d-1a3c-4543-922e-75112750adcc.png">

**Comment by 4everpheonix** [comment]
sorry but how did u run it?

**Comment by DOKKAEBIx** [comment]
even when run correctly I have the same issue

Traceback (most recent call last):
  File "Hazard.py", line 444, in <module>
  File "Hazard.py", line 304, in main
  File "util\QR_Grabber.py", line 62, in QR_Grabber
AttributeError: 'NoneType' object has no attribute 'find'
[3512] Failed to execute script 'Hazard' due to unhandled exception!

**Comment by Rdimo** [comment]
download new update
